// src/institutions.js

export const US_INSTITUTIONS = [
  { name: "American University", ringgold: "8363" },
  { name: "Arizona State University", ringgold: "7864" },
  { name: "Auburn University", ringgold: "1383" },
  { name: "Augusta University", ringgold: "1421" },
  { name: "Baylor University", ringgold: "14643" },
  { name: "Boston College", ringgold: "6019" },
  { name: "Boston University", ringgold: "1846" },
  { name: "Brandeis University", ringgold: "8244" },
  { name: "Brown University", ringgold: "6752" },
  { name: "Bucknell University", ringgold: "4517" },
  { name: "California Digital Library", ringgold: "33320" },
  { name: "California State University Fullerton", ringgold: "14666" },
  { name: "California State University Northridge", ringgold: "14671" },
  { name: "Carnegie Mellon University", ringgold: "6612" },
  { name: "Case Western Reserve University", ringgold: "2546" },
  { name: "Catholic University of America", ringgold: "8365" },
  { name: "Clemson University", ringgold: "2545" },
  { name: "Colorado State University", ringgold: "3447" },
  { name: "Cornell University", ringgold: "5922" },
  { name: "Dartmouth College", ringgold: "3728" },
  { name: "Drexel University", ringgold: "6527" },
  { name: "Duke University", ringgold: "3065" },
  { name: "East Tennessee State University", ringgold: "4154" },
  { name: "Emory University", ringgold: "1371" },
  { name: "Florida International University", ringgold: "5450" },
  { name: "Florida State University", ringgold: "7823" },
  { name: "Fred Hutchinson Cancer Research Center", ringgold: "7286" },
  { name: "George Washington University", ringgold: "8367" },
  { name: "Georgetown University", ringgold: "8368" },
  { name: "Georgetown University Medical Center", ringgold: "12231" },
  { name: "Georgia Institute of Technology", ringgold: "1372" },
  { name: "Georgia State University", ringgold: "1373" },
  { name: "Harvard University", ringgold: "1812" },
  { name: "Harvard Medical School", ringgold: "1811" },
  { name: "Howard University", ringgold: "8369" },
  { name: "Indiana University Bloomington", ringgold: "1771" },
  { name: "Iowa State University", ringgold: "1177" },
  { name: "Johns Hopkins University", ringgold: "1466" },
  { name: "Marymount University", ringgold: "1298" },
  { name: "Massachusetts Institute of Technology", ringgold: "2167" },
  { name: "Michigan State University", ringgold: "3078" },
  { name: "Mississippi State University", ringgold: "5547" },
  { name: "Montana State University Bozeman", ringgold: "33052" },
  { name: "New York University", ringgold: "5894" },
  { name: "North Carolina State University", ringgold: "6798" },
  { name: "Northeastern University", ringgold: "1848" },
  { name: "Northwestern University", ringgold: "3270" },
  { name: "Ohio State University", ringgold: "2647" },
  { name: "Oklahoma State University Stillwater", ringgold: "7618" },
  { name: "Old Dominion University", ringgold: "6042" },
  { name: "Oregon State University", ringgold: "2694" },
  { name: "Pennsylvania State University", ringgold: "8082" },
  { name: "Princeton University", ringgold: "6740" },
  { name: "Purdue University", ringgold: "311308" },
  { name: "RTI International", ringgold: "6856" },
  { name: "Rutgers The State University of New Jersey", ringgold: "242612" },
  { name: "Southern Methodist University", ringgold: "2765" },
  { name: "Stanford University", ringgold: "6429" },
  { name: "SUNY College at Buffalo", ringgold: "14791" },
  { name: "Temple University", ringgold: "6558" },
  { name: "Texas A&M University System", ringgold: "2655" },
  { name: "Texas Christian University", ringgold: "3402" },
  { name: "Texas Tech University", ringgold: "6177" },
  { name: "Tufts University", ringgold: "1810" },
  { name: "Tulane University", ringgold: "5783" },
  { name: "University of Alabama", ringgold: "8063" },
  { name: "University of Alabama at Birmingham", ringgold: "9968" },
  { name: "University of Arizona", ringgold: "8041" },
  { name: "University of California Irvine", ringgold: "8788" },
  { name: "University of California Los Angeles", ringgold: "8783" },
  { name: "University of California San Diego", ringgold: "8784" },
  { name: "University of California San Francisco", ringgold: "8785" },
  { name: "University of California Santa Barbara", ringgold: "8786" },
  { name: "University of Cincinnati", ringgold: "2514" },
  { name: "University of Colorado Boulder", ringgold: "1877" },
  { name: "University of Connecticut", ringgold: "7712" },
  { name: "University of Delaware", ringgold: "5972" },
  { name: "University of Denver", ringgold: "2927" },
  { name: "University of the District of Columbia", ringgold: "8315" },
  { name: "University of Florida", ringgold: "3463" },
  { name: "University of Georgia", ringgold: "1355" },
  { name: "University of Illinois at Chicago", ringgold: "14681" },
  { name: "University of Illinois at Urbana-Champaign", ringgold: "14589" },
  { name: "University of Iowa", ringgold: "4083" },
  { name: "University of Kansas", ringgold: "4202" },
  { name: "University of Maryland Baltimore", ringgold: "12265" },
  { name: "University of Maryland School of Medicine", ringgold: "12264" },
  { name: "University of Massachusetts Amherst", ringgold: "14707" },
  { name: "University of Michigan", ringgold: "1259" },
  { name: "University of Minnesota Twin Cities", ringgold: "5635" },
  { name: "University of Missouri Columbia", ringgold: "14716" },
  { name: "University of Nebraska-Lincoln", ringgold: "14719" },
  { name: "University of Nevada Las Vegas", ringgold: "14722" },
  { name: "University of New Hampshire", ringgold: "3067" },
  { name: "University of North Carolina at Chapel Hill", ringgold: "2331" },
  { name: "University of North Texas", ringgold: "3404" },
  { name: "University of Notre Dame", ringgold: "6111" },
  { name: "University of Oklahoma", ringgold: "6187" },
  { name: "University of Oregon", ringgold: "3265" },
  { name: "University of Pennsylvania", ringgold: "6572" },
  { name: "University of Pittsburgh", ringgold: "6614" },
  { name: "University of Rhode Island", ringgold: "4260" },
  { name: "University of Rochester", ringgold: "6927" },
  { name: "University of Southern California", ringgold: "5116" },
  { name: "University of Tennessee Knoxville", ringgold: "4292" },
  { name: "University of Texas at Arlington", ringgold: "12329" },
  { name: "University of Texas at Austin", ringgold: "12330" },
  { name: "University of Texas at Dallas", ringgold: "12335" },
  { name: "University of Texas at San Antonio", ringgold: "12346" },
  { name: "University of Texas MD Anderson Cancer Center", ringgold: "4002" },
  { name: "University of Texas Southwestern Medical Center at Dallas", ringgold: "12334" },
  { name: "University of Utah", ringgold: "7060" },
  { name: "University of Virginia", ringgold: "2358" },
  { name: "University of Washington", ringgold: "7284" },
  { name: "University of Wisconsin Madison", ringgold: "5228" },
  { name: "University of Wyoming", ringgold: "4416" },
  { name: "Virginia Commonwealth University", ringgold: "6889" },
  { name: "Virginia Polytechnic Institute and State University", ringgold: "1757" },
  { name: "Washington State University", ringgold: "6760" },
  { name: "Washington University in Saint Louis", ringgold: "7548" },
  { name: "West Virginia University", ringgold: "5631" },
  { name: "William & Mary", ringgold: "8604" },
  { name: "Yale University", ringgold: "5755" }
];

export const UK_INSTITUTIONS = [
  { name: "Aberystwyth University", ringgold: "1026" },
  { name: "Anglia Ruskin University", ringgold: "2369" },
  { name: "Arts University Bournemouth", ringgold: "6656" },
  { name: "Aston University", ringgold: "1722" },
  { name: "Bangor University", ringgold: "1506" },
  { name: "Bath Spa University", ringgold: "1554" },
  { name: "Birkbeck College", ringgold: "4894" },
  { name: "Birmingham City University", ringgold: "1725" },
  { name: "Bishop Grosseteste University", ringgold: "4545" },
  { name: "Bournemouth University", ringgold: "6657" },
  { name: "Brunel University", ringgold: "3890" },
  { name: "Buckinghamshire New University", ringgold: "3889" },
  { name: "Canterbury Christ Church University", ringgold: "2238" },
  { name: "Cardiff Metropolitan University", ringgold: "11352" },
  { name: "Cardiff Metropolitan University", ringgold: "6003" },
  { name: "Cardiff University", ringgold: "2112" },
  { name: "Central School of Speech and Drama", ringgold: "4685" },
  { name: "City, University of London", ringgold: "4895" },
  { name: "Conservatoire for Dance and Drama", ringgold: "129368" },
  { name: "Courtauld Institute of Art", ringgold: "4897" },
  { name: "Coventry University", ringgold: "2706" },
  { name: "Cranfield University", ringgold: "2717" },
  { name: "De Montfort University", ringgold: "4487" },
  { name: "Durham University", ringgold: "3057" },
  { name: "Edge Hill University", ringgold: "6249" },
  { name: "Edinburgh College of Art (Now part of the University of Edinburgh)", ringgold: "11994" },
  { name: "Edinburgh Napier University", ringgold: "3121" },
  { name: "Falmouth University", ringgold: "3314" },
  { name: "Glasgow Caledonian University", ringgold: "3525" },
  { name: "Glasgow School of Art", ringgold: "3517" },
  { name: "Glyndwr University", ringgold: "8725" },
  { name: "Goldsmiths College, University of London", ringgold: "4898" },
  { name: "Guildhall School of Music and Drama", ringgold: "4691" },
  { name: "Harper Adams University College", ringgold: "6000" },
  { name: "Heriot-Watt University", ringgold: "3120" },
  { name: "Heythrop College, University of London", ringgold: "4899" },
  { name: "Imperial College London", ringgold: "4615" },
  { name: "Institute of Cancer Research", ringgold: "5053" },
  { name: "Institute of Education", ringgold: "4901" },
  { name: "Keele University", ringgold: "4212" },
  { name: "King's College London", ringgold: "4616" },
  { name: "Kingston University", ringgold: "4264" },
  { name: "Lancaster University", ringgold: "4396" },
  { name: "Leeds Beckett University", ringgold: "4467" },
  { name: "Leeds College of Music", ringgold: "4459" },
  { name: "Leeds Trinity University (formerly Leeds Trinity and All Saints)", ringgold: "12054" },
  { name: "Liverpool Hope University", ringgold: "4588" },
  { name: "Liverpool Institute for Performing Arts", ringgold: "11584" },
  { name: "Liverpool John Moores University", ringgold: "4589" },
  { name: "Liverpool School of Tropical Medicine", ringgold: "9655" },
  { name: "London Business School", ringgold: "4092" },
  { name: "London Metropolitan University", ringgold: "4904" },
  { name: "London School of Economics & Political Science", ringgold: "4905" },
  { name: "London School of Hygiene & Tropical Medicine", ringgold: "4906" },
  { name: "London South Bank University", ringgold: "4914" },
  { name: "Loughborough University", ringgold: "5156" },
  { name: "Manchester Metropolitan University", ringgold: "5289" },
  { name: "Middlesex University", ringgold: "4907" },
  { name: "Newcastle University", ringgold: "5994" },
  { name: "Newman University", ringgold: "1713" },
  { name: "Northern School of Contemporary Dance", ringgold: "12050" },
  { name: "Northumbria University", ringgold: "5995" },
  { name: "Norwich University College of the Arts", ringgold: "6103" },
  { name: "Nottingham Trent University", ringgold: "6122" },
  { name: "Oxford Brookes University", ringgold: "6395" },
  { name: "Queen's University Belfast", ringgold: "1596" },
  { name: "Queen Margaret University", ringgold: "3122" },
  { name: "Queen Mary, University of London", ringgold: "4617" },
  { name: "Ravensbourne College of Design and Communication", ringgold: "2482" },
  { name: "Robert Gordon University", ringgold: "1018" },
  { name: "Roehampton University", ringgold: "4920" },
  { name: "Rose Bruford College", ringgold: "11637" },
  { name: "Royal Academy of Music", ringgold: "5291" },
  { name: "Royal Agricultural University (formerly Royal Agricultural College)", ringgold: "2522" },
  { name: "Royal College of Art", ringgold: "4910" },
  { name: "Royal College of Music", ringgold: "4911" },
  { name: "Royal Conservatoire of Scotland", ringgold: "3519" },
  { name: "Royal Holloway, University of London", ringgold: "3162" },
  { name: "Royal Northern College of Music", ringgold: "5290" },
  { name: "Royal Veterinary College, University of London", ringgold: "4912" },
  { name: "Royal Welsh College of Music & Drama", ringgold: "57340" },
  { name: "School of Oriental and African Studies", ringgold: "4913" },
  { name: "Scottish Agricultural College", ringgold: "3123" },
  { name: "Sheffield Hallam University", ringgold: "7314" },
  { name: "Southampton Solent University", ringgold: "7422" },
  { name: "Staffordshire University", ringgold: "7703" },
  { name: "St George's University of London", ringgold: "4915" },
  { name: "St Mary's University College, Twickenham", ringgold: "62693" },
  { name: "St Mary's University College Belfast", ringgold: "1598" },
  { name: "Stranmillis University College", ringgold: "64576" },
  { name: "Swansea Metropolitan University  (UWTSD)", ringgold: "7758" },
  { name: "Swansea University", ringgold: "7759" },
  { name: "Teesside University", ringgold: "5462" },
  { name: "The Open University", ringgold: "5488" },
  { name: "Trinity Laban Conservatoire of Music and Dance", ringgold: "169323" },
  { name: "University College Birmingham", ringgold: "1711" },
  { name: "University College London  (School of Pharmacy)", ringgold: "12076" },
  { name: "University College London - UCL", ringgold: "4919" },
  { name: "University for the Creative Arts", ringgold: "121205" },
  { name: "University of Aberdeen", ringgold: "1019" },
  { name: "University of Abertay Dundee", ringgold: "3041" },
  { name: "University of Bath", ringgold: "1555" },
  { name: "University of Bedfordshire", ringgold: "5195" },
  { name: "University of Birmingham", ringgold: "1724" },
  { name: "University of Bolton", ringgold: "1796" },
  { name: "University of Bradford", ringgold: "1905" },
  { name: "University of Brighton", ringgold: "1947" },
  { name: "University of Bristol", ringgold: "1980" },
  { name: "University of Cambridge", ringgold: "2152" },
  { name: "University of Central Lancashire", ringgold: "6723" },
  { name: "University of Chester", ringgold: "11965" },
  { name: "University of Chichester", ringgold: "2476" },
  { name: "University of Cumbria", ringgold: "9480" },
  { name: "University of Derby", ringgold: "2939" },
  { name: "University of Dundee", ringgold: "3042" },
  { name: "University of East Anglia - UEA", ringgold: "6106" },
  { name: "University of East London", ringgold: "4917" },
  { name: "University of Edinburgh", ringgold: "3124" },
  { name: "University of Essex", ringgold: "2591" },
  { name: "University of Exeter", ringgold: "3286" },
  { name: "University of Glasgow", ringgold: "3526" },
  { name: "University of Gloucestershire", ringgold: "2376" },
  { name: "University of Greenwich", ringgold: "4918" },
  { name: "University of Hertfordshire", ringgold: "3769" },
  { name: "University of Huddersfield", ringgold: "4013" },
  { name: "University of Hull", ringgold: "4019" },
  { name: "University of Kent", ringgold: "2240" },
  { name: "University of Leeds", ringgold: "4468" },
  { name: "University of Leicester", ringgold: "4488" },
  { name: "University of Lincoln", ringgold: "4547" },
  { name: "University of Liverpool", ringgold: "4591" },
  { name: "University of London", ringgold: "3163" },
  { name: "University of Manchester", ringgold: "5292" },
  { name: "University of Northampton", ringgold: "6087" },
  { name: "University of Nottingham", ringgold: "6123" },
  { name: "University of Oxford", ringgold: "6396" },
  { name: "University of Plymouth", ringgold: "6633" },
  { name: "University of Portsmouth", ringgold: "6697" },
  { name: "University of Reading", ringgold: "6816" },
  { name: "University of Salford", ringgold: "7046" },
  { name: "University of Sheffield", ringgold: "7315" },
  { name: "University of Southampton", ringgold: "7423" },
  { name: "University of South Wales", ringgold: "6654" },
  { name: "University of South Wales (Newport)", ringgold: "1027" },
  { name: "University of St Andrews", ringgold: "7486" },
  { name: "University of Stirling", ringgold: "7622" },
  { name: "University of St Mark and St John", ringgold: "6629" },
  { name: "University of Strathclyde", ringgold: "3527" },
  { name: "University of Suffolk", ringgold: "102099" },
  { name: "University of Sunderland", ringgold: "7735" },
  { name: "University of Surrey", ringgold: "3660" },
  { name: "University of Sussex", ringgold: "1948" },
  { name: "University of the Arts London", ringgold: "4903" },
  { name: "University of the Highlands and Islands", ringgold: "7709" },
  { name: "University of the West of England", ringgold: "1981" },
  { name: "University of the West of Scotland", ringgold: "6413" },
  { name: "University of Ulster", ringgold: "2596" },
  { name: "University of Wales Trinity St David", ringgold: "2284" },
  { name: "University of Wales Trinity St David", ringgold: "4393" },
  { name: "University of Wales Trinity St David", ringgold: "2284" },
  { name: "University of Warwick", ringgold: "2707" },
  { name: "University of West London", ringgold: "7364" },
  { name: "University of Westminster", ringgold: "4921" },
  { name: "University of Winchester", ringgold: "8629" },
  { name: "University of Wolverhampton", ringgold: "8695" },
  { name: "University of Worcester", ringgold: "8709" },
  { name: "University of York", ringgold: "8748" },
  { name: "Wellcome Trust", ringgold: "5072" },
  { name: "Writtle College", ringgold: "2366" },
  { name: "York St John University", ringgold: "41872" }
];
